# Generated by Django 3.2.5 on 2022-01-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220108_1535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
