# Generated by Django 3.2.5 on 2022-01-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('poemID', models.AutoField(primary_key=True, serialize=False)),
                ('lang', models.CharField(max_length=15)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('author', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
    ]
