# Generated by Django 3.2.5 on 2022-01-14 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220108_1535'),
        ('poetrydb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.user'),
        ),
    ]
