# Generated by Django 3.2.5 on 2022-01-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetrydb', '0002_alter_poem_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
    ]
