# Generated by Django 3.2.5 on 2022-01-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('poem_id', models.IntegerField()),
                ('user_commented', models.CharField(max_length=50)),
                ('comment_content', models.CharField(max_length=200)),
                ('comment_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
